services:
  db:
    image: mariadb:latest
    container_name: tohru_db
    env_file:
    - .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart:
      unless-stopped
    networks:
      - tohru

  bot:
    build: .
    container_name: tohru_bot
    env_file:
    - .env
    volumes:
      - uploads:/app/uploads
      - .:/app
    depends_on:
      - db
    restart:
      unless-stopped
    networks:
      - tohru

  web:
    image: php:8.2-apache
    container_name: tohru_web
    ports:
      - "80:80"
    volumes:
      - ./pages:/var/www/html:ro
      - ./uploads:/var/www/html/uploads
    environment:
      - PHP_DISPLAY_ERRORS=1
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - tohru
  
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    restart:
      unless-stopped
    networks:
      - tohru

volumes:
  db_data:
  uploads:

networks:
  tohru: